---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: fedora-gnome-wl
description: myOS Fedora GNOME with Broadcom wl driver

base-image: ghcr.io/myos-dev/fedora-gnome
image-version: latest

modules:
  - type: akmods
    base: main
    install:
      - wl